Replace existing Prometheus & Grafana with Kube-Prometheus
timescale/tobs pull request #123
Opened 2021-04-20 18:13 UTC by VineethReddy02

2021-05-03 06:24 UTC, VineethReddy02 commented on cli/cmd/prometheus/prometheusPortForward.go
> +	serviceName, err := k8s.KubeGetServiceName(root.Namespace, map[string]string{"release": root.HelmReleaseName, "app": "kube-prometheus-stack-prometheus"})
The labels here are hardcoded and in some other files as well. This will be fixed in upcoming refactoring.

2021-05-03 06:25 UTC, VineethReddy02 commented on cli/cmd/helm/version.go
> +const tobsVersion = "0.4.0"
There is no way currently to understand what version of `tobs` a user is using. So adding a new `version` cmd to know the tobs version being used.

2021-05-03 18:01 UTC, cevian requested changes
Some comments, overall looks good

2021-05-04 18:04 UTC, VineethReddy02 commented on chart/values.yaml
> +          - dashboards/k8s-hardware.json
I personally felt there is no single dashboard to measure cluster monitoring & hardware monitoring. All the dashboards are on K8s resource specific.

2021-05-04 18:05 UTC, VineethReddy02 commented on cli/cmd/helm/version.go
> +	fmt.Printf("Tobs Version: %s\n", tobsVersion)
You mean try to find the helm chart version of current deployed tobs? There can be a case where there is no tobs deployment yet.

2021-05-04 18:11 UTC, VineethReddy02 commented on chart/docs/upgrades.md
> +tobs upgrade
Yup only for helm specific upgrades. Updated the docs.

2021-05-04 18:14 UTC, VineethReddy02 commented on cli/cmd/helm/version.go
> +const tobsVersion = "0.4.0"
Automatically in the sense? From the CI during releases?

2021-05-04 18:17 UTC, VineethReddy02 commented on chart/values.yaml
> +  fullnameOverride: "tobs-kube-prometheus"
This is how the default names looks like with above provided override name:
```
NAMESPACE            NAME                                               READY   STATUS      RESTARTS   AGE
default              alertmanager-tobs-kube-prometheus-alertmanager-0   2/2     Running     0          99s
default              prometheus-tobs-kube-prometheus-prometheus-0       2/2     Running     1          99s
default              tobs-grafana-db-thcc7                              0/1     Completed   4          11m
default              tobs-grafana-dd54c76f9-hnqhg                       2/2     Running     0          2m13s
default              tobs-kube-prometheus-operator-fd544d7d9-8bb9v      1/1     Running     0          2m13s
default              tobs-kube-state-metrics-5fbc484f57-fqz97           1/1     Running     0          2m13s
default              tobs-prometheus-node-exporter-zmbrw                1/1     Running     0          2m13s
default              tobs-prometheus-permission-change-qvbjm            0/1     Completed   0          2m37s
default              tobs-promlens-7f778cc958-cvzq7                     1/1     Running     0          11m
default              tobs-promscale-d7fcf464c-9nf5f                     1/1     Running     6          11m
default              tobs-timescaledb-0                                 1/1     Running     0          11m
```

2021-05-05 16:39 UTC, cevian approved these changes
I think the version command output can still be improved, but happy to leave for a followup PR.

2021-05-05 16:39 UTC, cevian commented on chart/docs/upgrades.md
> +# Upgrading tobs using helm (without tobs CLI)
```suggestion
# Upgrading tobs using helm (without tobs CLI)

The following steps are necessary if using help without the tobs CLI. The tobs CLI will handle these upgrade tasks automatically for you.
```

2021-05-05 16:42 UTC, merged