Stack name override
timescale/tobs pull request #546
Opened 2022-08-15 18:52 UTC by nhudson

This will fix the issue with `kube-prometheus-stack` not taking the Helm name given at install time.

- Updated upgrade documentation to make sure that if you are upgrading that you should most likely add the option back.

#### Which issue this PR fixes

- fixes #247 

#### Checklist

- [x] Chart Version bumped
- [x] [CLA signed](https://cla-assistant.io/timescale/tobs)

2022-08-16 15:39 UTC, nhudson commented on chart/Chart.yaml
> +version: 12.1.1
No I knew that #545 would be bumping it to `12.1.0`.  I need to do a rebase though.

2022-08-16 15:40 UTC, nhudson commented on chart/docs/upgrades.md
> +Starting with tobs `12.1.0` Helm chart the `kube-prometheus-stack.fullNameOverride` option is removed.
Thanks!  I'll add that.

2022-08-16 15:43 UTC, nhudson commented
I plan on moving the `chart/docs` directory to be top level.  This is due to `ct`, with any changes in the `chart` directory it will auto bump the version and for most/all docs we shouldn't need to do that.

2022-08-16 17:19 UTC, nhudson commented
@onprem let me know if you have any other questions about this.

2022-08-18 09:21 UTC, paulfantom commented on chart/README.md
> +#set conceallevel=2 tobs Helm Charts
What does this do?

2022-08-18 09:23 UTC, paulfantom requested changes

2022-08-18 09:23 UTC, paulfantom commented on chart/Chart.yaml
> +version: 12.2.0
This is a breaking change as such we should bump to `13.0.0`.

2022-08-18 17:39 UTC, nhudson commented on chart/README.md
> +#set conceallevel=2 tobs Helm Charts
yup, this was a mistake on my end.

2022-08-22 13:03 UTC, onprem approved these changes
LGTM!

2022-08-22 13:20 UTC, merged